### ISSUE TITLE
[FEATURE REQUEST] optional header elements

### ISSUE THREAD

**Issue by prosidney** [ron2015schmitt/mat-ngx-tui-calendar#1]
Is it possible to make those header icons  configurable( on/ off)? 

For example 

I don't need the highlighted ones.

![Screenshot_20220202-193557_Firefox~2.jpg](https://user-images.githubusercontent.com/4601009/152217270-0075b48b-89f6-4381-bdb5-fe58da8dd35e.jpg)

**Comment by ron2015schmitt** [comment]
Should be possible.  I will take a look tonight.

**Comment by prosidney** [comment]
Nice....you da man...thanks

**Comment by ron2015schmitt** [comment]
Thanks man.
Give the latest release a try: v12.1.2

**Comment by prosidney** [comment]
Yes, I just tested it, it works like a charm. Thanks very much
