### ISSUE TITLE
Error when importing the NgxMatTuiCalendarModule from a lazy loaded module

### ISSUE THREAD

**Issue by prosidney** [ron2015schmitt/mat-ngx-tui-calendar#2]
In this scenario I get the below error

Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

Looking a bit the angular documentation, it seems the BrowserModule should only be loaded once by the main module and since it is also being imported within the NgxMatTuiCalendarModule I must only import NgxMatTuiCalendarModule in the app.module, the problem with that is that the initial bundle size increases almost 1MB mainly because of the tui-calendar

Big initial bundle size is not good for the UX since it takes more time to load on bad internet connections or low end devices, it also decreases the score for google SEO.

Can we have support lazy loading ?

Thanks in advance

**Comment by ron2015schmitt** [comment]
Ok, give 12.1.3 a try and let me know how it goes.

**Comment by prosidney** [comment]
Hi,

I tried with the 12.1.3 and the error is still there.

**Comment by prosidney** [comment]
Hey, I'm thinking about some close work colaboration  here, is there an email or zoom contact I can be using to talk with you?

have a nice week
